name: Action

on:
  push:
    branches:
      - main  # default branch
jobs:
  do_action:
    runs-on: ubuntu-latest
    steps:
      - name: checkout crawlAction
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SHADOW_TOKEN }}
          repository: shadowprompt/crawl
          path: ./.github/actions/crawlAction
      - name: run crawlAction
        id: step2
        uses: ./.github/actions/crawlAction
        with:
          timeout: 10000
          handlerPath: shanghai/house/gdgzf
      - run: |
          echo ${{steps.step2.outputs.crawlResult}}
      - name: run notifyAction
        uses: daoAction/notify/@main
        with:
          ids: ${{ secrets.BARK_IDS }}
          body: ${{steps.step2.outputs.crawlError}}
