name: Do

on:
  schedule:
    # * 每5分钟一次
    - cron:  '0/15 * * * *'
  push:
    branches:
      - main  # default branch
jobs:
  do_schedule:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        name: Do daozhaoActionWait
        uses: shadowprompt/daozhaoAction/@main
        with:
          # number of milliseconds to wait
          milliseconds: 15000
      - run: |
          echo ${{steps.step1.outputs.time}}
      - id: step2
        name: Do crawlAction
        uses: shadowprompt/crawl/@main
        with:
          timeout: 10000
      - run: |
          echo ${{steps.step2.outputs.crawlResult}}
