name: Do

on:
  schedule:
    # * 每5分钟一次
    - cron:  '* 0/12 * * *'
  push:
    branches:
      - main  # default branch
jobs:
  do_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: echo token
        run: |
          echo "---my SHADOW_TOKEN"
      - name: Do daozhaoActionWait
        id: step1
        uses: shadowprompt/daozhaoAction/@main
        with:
          # number of milliseconds to wait
          milliseconds: 15000
      - run: |
          echo ${{steps.step1.outputs.time}}
      - name: checkout crawlAction
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SHADOW_TOKEN }}
          repository: shadowprompt/crawl
          path: ./.github/actions/crawlAction
      - name: run crawlAction
        id: step2
        uses: ./.github/actions/crawlAction
        with:
          timeout: 10000
          handlerPath: shanghai/house/gycqbzf/error
      - run: |
          echo ${{steps.step2.outputs.crawlResult}}
