name: Do

on:
  schedule:
    # * 每5分钟一次
    - cron:  '* 0/12 * * *'
  push:
    branches:
      - main  # default branch
jobs:
  do_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: echo token
        run: |
          echo ${{secrets.SHADOW_TOKEN}}
          echo "---"
          echo ${{secrets.ACCESS_TOKEN}}
      - id: step1
        name: Do daozhaoActionWait
        uses: shadowprompt/daozhaoAction/@main
        with:
          # number of milliseconds to wait
          milliseconds: 15000
           # Personal access token to check out private repository
          token: ${{ secrets.ACCESS_TOKEN }}
      - run: |
          echo ${{steps.step1.outputs.time}}
      - id: step2
        name: Do crawlAction
        uses: shadowprompt/crawl/@main
        with:
          timeout: 10000
          handlerPath: shanghai/house/gycqbzf
      - run: |
          echo ${{steps.step2.outputs.crawlResult}}
