name: Do

on:
  schedule:
    # * 每5分钟一次
    - cron:  '* 0/12 * * *'
  push:
    branches:
      - main  # default branch
jobs:
  do_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: echo token
        run: |
          echo ${{secrets.SHADOW_TOKEN}}
          echo "---"
          echo ${{secrets.ACCESS_TOKEN}}
