name: Schedule

on:
  schedule:
    # * 每5分钟一次
    - cron:  '* 0/12 * * *'
  workflow_dispatch:
    branches:
      - main
jobs:
  do_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: echo token
        run: |
          echo "---my SHADOW_TOKEN"
      - name: Do wait action
        id: step1
        uses: daoAction/wait/@main
        with:
          # number of milliseconds to wait
          milliseconds: 15000
      - run: |
          echo ${{steps.step1.outputs.time}}
